/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /home/tianjiao/cyclone_version/cyclonev1.2_test/VehicleData.idl
  Source: VehicleData.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "VehicleData.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace VehicleData
{
std::ostream& operator<<(std::ostream& os, steeringWheel const& rhs)
{
  (void) rhs;
  os << "[";
  os << "vehicle_id: " << rhs.vehicle_id();
  os << ", lX: " << rhs.lX();
  os << ", lY: " << rhs.lY();
  os << ", lRz: " << rhs.lRz();
  os << ", rglSlider_0: " << rhs.rglSlider_0();
  os << ", buttons: " << rhs.buttons();
  os << "]";
  return os;
}

} //namespace VehicleData

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::VehicleData::steeringWheel>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::vehicle_id
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::lX
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::lY
  props.push_back(entity_properties_t(1, 3, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::lRz
  props.push_back(entity_properties_t(1, 4, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::rglSlider_0
  props.push_back(entity_properties_t(1, 5, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::buttons

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

